# Generated by Django 5.2.7 on 2025-10-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(null=True, upload_to='images/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
